/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#e5eeff",
        "on-tertiary-fixed-variant": "#005236",
        "primary-fixed": "#dbe1ff",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#213145",
        "on-primary-fixed": "#00174b",
        "secondary": "#4648d4",
        "inverse-primary": "#b4c5ff",
        "surface-bright": "#f8f9ff",
        "primary-container": "#2563eb",
        "surface-tint": "#0053db",
        "on-secondary-container": "#fffbff",
        "background": "#f8f9ff",
        "outline-variant": "#c3c6d7",
        "surface-container-low": "#eff4ff",
        "primary": "#004ac6",
        "tertiary-container": "#007d55",
        "tertiary": "#006242",
        "on-surface": "#0b1c30",
        "on-primary-fixed-variant": "#003ea8",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#c0c1ff",
        "on-tertiary-fixed": "#002113",
        "secondary-container": "#6063ee",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#6ffbbe",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container-high": "#dce9ff",
        "on-error-container": "#93000a",
        "surface": "#f8f9ff",
        "on-secondary-fixed": "#07006c",
        "on-secondary-fixed-variant": "#2f2ebe",
        "on-tertiary-container": "#bdffdb",
        "surface-variant": "#d3e4fe",
        "outline": "#737686",
        "surface-dim": "#cbdbf5",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-container": "#eeefff",
        "on-background": "#0b1c30",
        "secondary-fixed": "#e1e0ff",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#b4c5ff",
        "surface-container-highest": "#d3e4fe",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#434655",
        "on-error": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-sm": "0.5rem",
        "space-xl": "2rem",
        "gutter": "1rem",
        "space-md": "1rem",
        "margin": "1.25rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem"
      },
      fontFamily: {
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg": ["30px", { lineHeight: "38px", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
